import { test, expect } from '@playwright/test'
const band = { id: 'band-1', slug: 'tobago-carnival', name: 'Tobago Carnival', eventYear: 2026, eventLabel: 'Carnival', tagline: 'Catch the vibe', brand: {}, entitlements: ['truck_tracker','updates','guide'], liveModules: ['truck_tracker','updates','guide'], comingOnline: [], upsells: {}, catalog: [] }
const truck = { name: 'Carnival truck', publicLive: false, status: 'not-live', message: 'Not on the road yet', meetup: { lat:11.18,lng:-60.73,label:'Scarborough — to be confirmed' }, position: null, serverTime: new Date().toISOString() }
test.beforeEach(async ({ page }) => {
  await page.route('**/api/auth/me', r => r.fulfill({ json: { user: null } }))
  await page.route('**/api/public/bands', r => r.fulfill({ json: { bands: [band] } }))
  await page.route('**/api/public/bands/tobago-carnival', r => r.fulfill({ json: { band } }))
  await page.route('**/api/public/bands/tobago-carnival/tracker', r => r.fulfill({ json: { truck } }))
})
test('live route loads without upsell; disconnected tracker hides position', async ({ page }) => {
  await page.goto('/tobago-carnival')
  await expect(page.getByRole('heading', { name: 'Find the truck' })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Not on the road yet/ })).toBeVisible()
  await page.route('**/api/public/bands/tobago-carnival/tracker', r => r.abort())
  await expect(page.getByText('Connection interrupted.', { exact: false })).toBeVisible({ timeout:15000 })
  await expect(page.getByRole('button', { name:'Try again' })).toBeVisible()
})
test('band outages offer retry rather than claiming band does not exist', async ({ page }) => {
  await page.route('**/api/public/bands/tobago-carnival', r => r.fulfill({ status:503, json:{error:{message:'Unavailable'}} }))
  await page.goto('/tobago-carnival')
  await expect(page.getByText('Could not connect.', { exact:false })).toBeVisible()
  await page.route('**/api/public/bands/tobago-carnival', r => r.fulfill({ json:{band} }))
  await page.getByRole('button',{name:'Try again'}).click()
  await expect(page.getByRole('heading',{name:'Find the truck'})).toBeVisible()
})
test('local photos survive picker close and enforce total across batches', async ({ page }) => {
  await page.goto('/demo/photos')
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64')
  await page.getByRole('button',{name:'Add photos',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles({ name:'preview.png',mimeType:'image/png',buffer:png })
  await page.getByRole('button',{name:/Add 1 photo/}).click()
  const preview = page.locator('img[alt="preview"]')
  await expect(preview).toBeVisible()
  await expect.poll(() => preview.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(1)
  await page.getByRole('button',{name:'Add photos',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles(Array.from({length:20},(_,i) => ({name:`photo${i}.png`,mimeType:'image/png',buffer:png})))
  await page.getByRole('button',{name:/Add 19 photos/}).click()
  await expect(page.getByRole('button',{name:'Add photos',exact:true})).toBeDisabled()
  await expect(page.getByText('20 local previews added')).toBeVisible()
})
test('admin action failures are visible and buttons recover', async ({ page }) => {
  const user = { id:'u', email:'admin@example.test', name:'Admin', platformRole:'platform_admin', bandRoles:[], mustResetPassword:false }
  await page.route('**/api/auth/me', r => r.fulfill({json:{user}}))
  await page.route('**/api/platform/bands?*', r => r.fulfill({json:{bands:[{...band,entitlements:[]}],hasMore:false}}))
  await page.route('**/api/platform/users?*', r => r.fulfill({json:{users:[],hasMore:false}}))
  await page.route('**/api/platform/requests?*', r => r.fulfill({json:{requests:[],hasMore:false}}))
  await page.route('**/api/platform/bands/*/entitlements', r => r.fulfill({status:503,json:{error:{message:'Activation failed. Please retry.'}}}))
  await page.goto('/platform')
  await page.getByRole('button',{name:'Activate',exact:true}).first().click()
  await expect(page.getByText('Activation failed. Please retry.')).toBeVisible()
  await expect(page.getByRole('button',{name:'Activate',exact:true}).first()).toBeEnabled()
})
test('guide falls back to its public cached copy on connection failure', async ({ page }) => {
  await page.route('**/api/public/bands/tobago-carnival/content/guide', r => r.fulfill({json:{content:{title:'Your day',location:'Scarborough',schedule:['To be confirmed'],notes:['Follow your marshal']},updatedAt:new Date().toISOString()}}))
  await page.goto('/tobago-carnival/guide')
  await expect(page.getByText('Follow your marshal')).toBeVisible()
  await page.route('**/api/public/bands/tobago-carnival/content/guide', r => r.abort())
  await page.reload()
  await expect(page.getByText('Offline copy', {exact:false})).toBeVisible()
  await expect(page.getByText('Follow your marshal')).toBeVisible()
})
test('location denial leaves the tracker usable', async ({ page, context }) => {
  await context.clearPermissions()
  await page.goto('/tobago-carnival')
  await page.getByRole('button',{name:'Show my location'}).click()
  await expect(page.getByText('Location was unavailable.',{exact:false})).toBeVisible({timeout:20000})
  await expect(page.getByRole('heading',{name:'Find the truck'})).toBeVisible()
})
