import type { Brand } from "./types.ts"

export const fogAngelsBrand: Brand = {
  id: "fog-angels",
  productName: "Fog Angels",
  bandName: "Fog Angels Carnival",
  bandSlug: "fog-angels",
  eventYear: 2026,
  eventLabel: "Fantasy Island · 29 Oct – 4 Nov",
  tagline: "A world beyond imagination.",
  heroTitle: "Find the truck",
  kicker: "Welcome to Fantasy Island",
  logoSrc: "/brands/fog-angels/logo.webp",
  logoWide: true,
  fontDisplay: '"Cinzel", ui-serif, Georgia, serif',
  footerLine:
    "Fog Angels Carnival · Fantasy Island 2026 — assistive location when tracking is live. Marshals over the map.",
  fontsHref: "https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap",
  logoPlaceholder: {
    monogram: "FA",
    caption: "Fog Angels",
  },
  palette: {
    night: "#080518",
    panel: "#0d0a1e",
    raised: "#1a1335",
    line: "#3d2a58",
    ink: "#f8f4ea",
    muted: "#c4b5d4",
    faint: "#aa99bd",
    gold: "#f5c25a",
    goldink: "#3a230a",
    teal: "#9bd4ff",
    live: "#3ddc97",
    warn: "#f5a524",
    sky: "#c4b5fd",
    danger: "#f87171",
  },
  contact: {
    phone: "",
    whatsapp: "",
    email: "",
    instagram: "https://www.instagram.com/fogangelscarnival/",
    website: "https://fogangels.com/",
  },
  registrationUrl: "https://fogangels.com/",
  visuals: {
    heroSrc: "/brands/fog-angels/fantasy-island.jpg",
    atmosphereSrc: "/brands/fog-angels/island-night.jpg",
    gallery: [
      {
        src: "/brands/fog-angels/genie.jpg",
        title: "Make a wish",
        alt: "Fog Angels Fantasy Island character art",
        category: "pretty-mas",
      },
      {
        src: "/brands/fog-angels/fantasy-island.jpg",
        title: "Welcome to Fantasy Island",
        alt: "Fog Angels Fantasy Island floating palace",
        category: "pretty-mas",
      },
      {
        src: "/brands/fog-angels/pretty-mas.jpg",
        title: "Gold on the road",
        alt: "Gold and black Pretty Mas costume on a carnival truck",
        category: "pretty-mas",
      },
      {
        src: "/brands/fog-angels/truck.jpg",
        title: "Fantasy Island truck",
        alt: "Gold carnival truck on a tropical night road",
        category: "pretty-mas",
      },
      {
        src: "/brands/fog-angels/gala.jpg",
        title: "The Gala",
        alt: "Pink and white gala terrace at sunset",
        category: "pretty-mas",
      },
      {
        src: "/brands/fog-angels/jouvert.jpg",
        title: "J’ouvert morning",
        alt: "Gold and purple paint on a Tobago road at dawn",
        category: "jouvert",
      },
      {
        src: "/brands/fog-angels/island-night.jpg",
        title: "Island after dark",
        alt: "Fantasy Island floating at night above a gold portal",
        category: "jouvert",
      },
      {
        src: "/brands/fog-angels/portal-close.jpg",
        title: "The portal",
        alt: "Golden celestial portal above tropical clouds",
        category: "jouvert",
      },
    ],
  },
  presentation: {
    slug: "fog-angels",
    name: "Fog Angels Carnival",
    eventYear: 2026,
    eventLabel: "Fantasy Island · 29 Oct – 4 Nov",
    tagline: "A world beyond imagination.",
    truckName: "Fantasy Island truck",
    meetup: {
      lat: 11.1512,
      lng: -60.8388,
      label: "Chill Out Bar, Milford Road, Tobago — confirm with your section on the day",
    },
    updates: [
      {
        id: "welcome",
        title: "Welcome to Fantasy Island",
        body: "This is Fog Angels on the road. When the crew goes live, the pin is the Fantasy Island truck. Follow your marshals if the map and the road disagree.",
        imageSrc: "/brands/fog-angels/fantasy-island.jpg",
      },
      {
        id: "meetup",
        title: "Meet at Chill Out Bar",
        body: "Crew reference is Chill Out Bar on Milford Road. Exact line-up can move — ask your section leader before you travel.",
        imageSrc: "/brands/fog-angels/truck.jpg",
      },
    ],
    guide: {
      title: "Fantasy Island 2026",
      location: "Chill Out Bar, Milford Road, Tobago — confirm with crew",
      coverSrc: "/brands/fog-angels/fantasy-island.jpg",
      schedule: [
        "Tobago Carnival — 29 October to 4 November 2026",
        "Carnival Friday — Stink N Dutty 3 a.m., J’ouvert 4 a.m., Sand Jam 10 a.m. (confirm the date with your section)",
        "The Gala at Coco Reef — 3 p.m., pink and white (confirm with the band)",
        "Pretty Mas — follow the day’s call from marshals",
      ],
      notes: [
        "Bring water, comfortable shoes and your Fog Angels booking details.",
        "Follow the marshals on the road. The map is a guide, not official routing or an emergency service.",
        "Truck positions come from a crew phone while sharing is active. Check the update age before heading toward the pin.",
        "Registration and the band story live at fogangels.com. Road pictures and calls: instagram.com/fogangelscarnival.",
      ],
    },
  },
}
